name: Playwright E2E Tests

on:
  deployment_status:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  preview:
    uses: DoctorDerek/DoctorDerekCICD/.github/workflows/playwright.yml@0bcbfc0a2e2a8f210e3d445a92615f5701591f17
    with:
      trusted-oidc: true
